openapi: 3.0.3
info:
  title: FantaF1 BFF API
  description: BFF API che chiama i servizi /dati per recuperare le informazioni sui piloti. Tutte le richieste richiedono un JWT valido presente nel cookie denominato `auth-token`.
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Server BFF di sviluppo locale

paths:
  /fantaf1-bff/piloti:
    get:
      summary: Restituisce la lista dei piloti per un anno specifico (chiamando /dati/piloti)
      operationId: getPilotiFromDati
      tags:
        - Dati
      security:
        - cookieAuth: [ ]
      parameters:
        - name: anno
          in: query
          description: Anno della stagione
          required: true
          schema:
            type: integer
            example: 2025
      responses:
        "200":
          description: Lista piloti recuperata tramite il servizio dati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pilota"
        "401":
          description: Non autorizzato - Token mancante o invalido
        "403":
          description: Accesso vietato
        "500":
          description: Errore interno del server

  /fantaf1-bff/piloti-con-costo:
    get:
      summary: Restituisce la lista dei piloti con costo per un anno specifico (aggregata dal servizio dati)
      operationId: getPilotiConCostoFromDati
      tags:
        - Dati
      security:
        - cookieAuth: [ ]
      parameters:
        - name: anno
          in: query
          description: Anno della stagione
          required: true
          schema:
            type: integer
            example: 2025
      responses:
        "200":
          description: Lista piloti con costo recuperata tramite il servizio dati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PilotaConCosto"
        "401":
          description: Non autorizzato - Token mancante o invalido
        "403":
          description: Accesso vietato
        "500":
          description: Errore interno del server

  /fantaf1-bff/piloti/{id}:
    get:
      summary: Restituisce i dettagli di un pilota tramite ID (chiamando /dati/piloti/{id})
      operationId: getPilotaByIdFromDati
      tags:
        - Dati
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Dettaglio pilota recuperato tramite il servizio dati
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pilota"
        "401":
          description: Non autorizzato - Token mancante o invalido
        "403":
          description: Accesso vietato
        "404":
          description: Pilota non trovato
        "500":
          description: Errore interno del server

  /fantaf1-bff/limite-scelta:
    get:
      summary: Restituisce i dati della prossima gara e la scadenza per effettuare le scelte
      operationId: getLimiteScelta
      tags:
        - Dati
      security:
        - cookieAuth: [ ]
      responses:
        "200":
          description: Informazioni sulla prossima gara e scadenza per le selezioni
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimiteSceltaResponse"
        "401":
          description: Non autorizzato - Token mancante o invalido nel cookie
        "403":
          description: Accesso vietato
        "500":
          description: Errore interno del server

  /fantaf1-bff/login:
    post:
      summary: Effettua il login e ottiene il JWT
      operationId: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login effettuato con successo, JWT restituito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtResponse"
        "400":
          description: Richiesta errata - Dati mancanti o non validi
        "401":
          description: Credenziali errate
        "500":
          description: Errore interno del server

  /fantaf1-bff/piloti/{id}/aggiorna-costo:
    post:
      summary: Aggiorna il costo di un pilota dato il suo ID
      operationId: aggiornaCostoPilota
      tags:
        - Dati
      security:
        - cookieAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: ID del pilota
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AggiornaCostoRequest'
      responses:
        "200":
          description: Costo aggiornato con successo
        "400":
          description: Richiesta non valida
        "401":
          description: Non autorizzato
        "404":
          description: Pilota non trovato
        "500":
          description: Errore interno del server

  /fantaf1-bff/selezione:
    post:
      summary: Seleziona i piloti e circuiti per un weekend di gara
      description: Endpoint per inviare la selezione di un utente per un GP specifico
      operationId: selezionePiloti
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelezioneRequest'
      responses:
        "200":
          description: Selezione registrata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelezioneResponse'
        "400":
          description: Errore di validazione input
        "401":
          description: Token non valido o mancante
        "500":
          description: Errore interno del server
    get:
      summary: Restituisce la selezione effettuata dall’utente autenticato per un GP specifico e i crediti rimanenti
      description: Endpoint per recuperare la selezione di un utente autenticato per un determinato GP, insieme ai crediti residui.
      operationId: getSelezionePiloti
      security:
        - cookieAuth: [ ]
      parameters:
        - name: gpWeekendId
          in: query
          required: true
          schema:
            type: integer
            example: 7
      responses:
        '200':
          description: Selezione trovata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelezioneConCreditiResponse'
        '400':
          description: Parametri non validi
        '401':
          description: Non autorizzato - token mancante o non valido
        '404':
          description: Selezione non trovata
        '500':
          description: Errore interno del server


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth-token

  schemas:
    Pilota:
      type: object
      properties:
        id:
          type: integer
          example: 1
        driver_id:
          type: string
          example: "max_verstappen"
        sigla:
          type: string
          example: "VER"
        nome:
          type: string
          example: "Max"
        cognome:
          type: string
          example: "Verstappen"
        numero:
          type: integer
          format: int32
          example: 33
        nazionalita:
          type: string
          example: "Paesi Bassi"

    PilotaConCosto:
      type: object
      properties:
        id:
          type: integer
        driverId:
          type: string
        nome:
          type: string
        cognome:
          type: string
        sigla:
          type: string
        costo:
          type: integer
        numero:
          type: integer
        nazionalita:
          type: string

    LimiteSceltaResponse:
      type: object
      properties:
        id:
          type: integer
          example: 2
        raceName:
          type: string
          example: "Chinese Grand Prix"
        circuitName:
          type: string
          example: "Shanghai International Circuit"
        country:
          type: string
          example: "China"
        dateTimeRace:
          type: string
          format: date-time
          example: "2025-03-23T08:00:00+01:00"
        urlWikipedia:
          type: string
          example: "https://en.wikipedia.org/wiki/2025_Chinese_Grand_Prix"
        scadenzaScelte:
          type: string
          format: date-time
          example: "2025-03-21T04:30:00+01:00"
        scelteAperte:
          type: boolean
          example: true

    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: "fabrizio"
        password:
          type: string
          example: "superpassword123"

    JwtResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    AggiornaCostoRequest:
      type: object
      properties:
        nuovoValore:
          type: integer
          example: 45

    SelezioneRequest:
      type: object
      required:
        - gpWeekendId
        - driverIds
      properties:
        gpWeekendId:
          type: integer
          example: 7
        driverIds:
          type: array
          items:
            type: integer
          minItems: 3
          maxItems: 3
          example: [ 3, 8, 15 ]

    SelezioneResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "Selezione salvata correttamente"
        selectionId:
          type: integer
          example: 42

    SelezioneConCreditiResponse:
      type: object
      properties:
        gpWeekendId:
          type: integer
          example: 7
        driverIds:
          type: array
          items:
            type: integer
          example: [ 3, 8, 15 ]
        creditsRemaining:
          type: integer
          example: 85