openapi: 3.0.3
info:
  title: FantaF1 BFF API
  description: BFF API che chiama i servizi /dati per recuperare le informazioni sui piloti
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Server BFF di sviluppo locale

paths:
  /fantaf1-bff/piloti:
    get:
      summary: Restituisce la lista dei piloti per un anno specifico (chiamando /dati/piloti)
      operationId: getPilotiFromDati
      tags:
        - Dati
      parameters:
        - name: anno
          in: query
          description: Anno della stagione
          required: true
          schema:
            type: integer
            example: 2025
      responses:
        "200":
          description: Lista piloti recuperata tramite il servizio dati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pilota"

  /fantaf1-bff/piloti-con-costo:
    get:
      summary: Restituisce la lista dei piloti con costo per un anno specifico (aggregata dal servizio dati)
      operationId: getPilotiConCostoFromDati
      tags:
        - Dati
      parameters:
        - name: anno
          in: query
          description: Anno della stagione
          required: true
          schema:
            type: integer
            example: 2025
      responses:
        "200":
          description: Lista piloti con costo recuperata tramite il servizio dati
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PilotaConCosto"

  /fantaf1-bff/piloti/{id}:
    get:
      summary: Restituisce i dettagli di un pilota tramite ID (chiamando /dati/piloti/{id})
      operationId: getPilotaByIdFromDati
      tags:
        - Dati
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Dettaglio pilota recuperato tramite il servizio dati
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pilota"

  /fantaf1-bff/limite-scelta:
    get:
      summary: Restituisce i dati della prossima gara e la scadenza per effettuare le scelte
      operationId: getLimiteScelta
      tags:
        - Dati
      responses:
        "200":
          description: Informazioni sulla prossima gara e scadenza per le selezioni
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimiteSceltaResponse"

components:
  schemas:
    Pilota:
      type: object
      properties:
        id:
          type: integer
          example: 1
        driver_id:
          type: string
          example: "max_verstappen"
        sigla:
          type: string
          example: "VER"
        nome:
          type: string
          example: "Max"
        cognome:
          type: string
          example: "Verstappen"
        numero:
          type: integer
          format: int32
          example: 33
        nazionalita:
          type: string
          example: "Paesi Bassi"
    PilotaConCosto:
      type: object
      properties:
        id:
          type: integer
        driverId:
          type: string
        nome:
          type: string
        cognome:
          type: string
        sigla:
          type: string
        costo:
          type: integer
        numero:
          type: integer
        nazionalita:
          type: string
    LimiteSceltaResponse:
      type: object
      properties:
        id:
          type: integer
          example: 2
        raceName:
          type: string
          example: "Chinese Grand Prix"
        circuitName:
          type: string
          example: "Shanghai International Circuit"
        country:
          type: string
          example: "China"
        dateTimeRace:
          type: string
          format: date-time
          example: "2025-03-23T08:00:00+01:00"
        urlWikipedia:
          type: string
          example: "https://en.wikipedia.org/wiki/2025_Chinese_Grand_Prix"
        scadenzaScelte:
          type: string
          format: date-time
          example: "2025-03-21T04:30:00+01:00"
        scelteAperte:
          type: boolean
          example: true