spring:
  application:
  name: fantaf1-dati
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SECRET_KEY}

server:
  port: 8082

fantaf1:
  dati:
    base-url: http://localhost:8080
