spring:
  application:
    name: fantaf1-user
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
    port: 8083

jwt:
  secret-key: ${SECRET_KEY}