services:
  database:
    image: postgres:latest
    container_name: fantaf1-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fantaf1-db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: fantaf1-pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fantaf1.example.com # Cambiato da .local a .example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"

volumes:
  fantaf1-db-data:
