services:
  database:
    image: postgres:latest
    container_name: fantaf1-db-dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fantaf1-db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: fantaf1-adminer-dev
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database

volumes:
  fantaf1-db-data:
